### ISSUE TITLE
map_to_table confints formatted as percent on means

### ISSUE THREAD

**Issue by anjamarinag** [mabafaba/hypegrammaR#10]
what the title says

**Comment by ellieallien** [comment]
^Hahah 
@Martin how can map to table know the type of summary stat it came from and decide on % signs ? 
- from results$parameters 
- as an extra argument for each result we are mapping to table for 
- cut out % alltogether and just report proportions

Im good with all of those

**Comment by mabafaba** [comment]
From parameters$case - if/else was already implemented just hadn’t removed the % singn.. 
Fixed once pushed
