### ISSUE TITLE
flexible confidence level argument for from_analysisplan_map_to_output

### ISSUE THREAD

**Issue by boukepieter** [mabafaba/hypegrammaR#18]
Is it possible to add an argument to from_analysisplan_map_to_output to set the confidence level for the calculation of the confidence intervals? That would be great!
Or another easy solution to change the confidence level.

**Comment by mabafaba** [comment]
added as a parameter to development version b3f8b6fb7d9413fa90c65575577dd9b85ad286ff
Leaving this issue open until tested successfully

**Comment by mabafaba** [comment]
@boukepieter let me know if this works for you!

**Comment by boukepieter** [comment]
Sorry it doesn't yet, result is only NA's now... I tested it going back to the master version and then it was working again so it has something to do with the dev.
