### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by rolloverlime** [mabafaba/hypegrammaR#3]
When running:
`
remotes::install_github("mabafaba/hypegrammaR")
`

I get the following error:
```
Downloading GitHub repo mabafaba/koboquest@master
Error in untar2(tarfile, files, list, exdir) : incomplete block on file
In addition: Warning messages:
1: In if (is.character(con)) { :
  closing unused connection 4 (mabafaba-hypegrammaR-67b6628/tests/testthat/data.csv)
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
```

**Comment by mabafaba** [comment]
@rolloverlime thanks a lot for the issue report!

it appears that the download got corrupted; did you get this exact error multiple times?
generally try running
```
install.packages("devtools")
```
and then use
```
devtools::install_github(...)
```
instead of `remotes`.
seems to resolve a few of the issues we've seen

**Comment by agualtieri** [comment]
When I try to install using `devtools::install_github(...)`

It returns the following error: `Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error`

This might be useful too `ERROR: dependencies 'survey', 'surveyweights' are not available for package 'hypegrammaR'`
