### ISSUE TITLE
hypegrammaR::load_samplingframe() not working

### ISSUE THREAD

**Issue by boukepieter** [mabafaba/hypegrammaR#8]
hypegrammaR::load_samplingframe() seems not to be working. It looks that the names of a non existent dataset 'data' is tried to be changed while the dataset is actually called 'samplingframe'.

**Comment by mabafaba** [comment]
as you said it's the
```
names(data)<-to_alphanumeric(names(data)) 
```
line that should be on the samplingframe! pull req?
Thanks a ton!

**Comment by mabafaba** [comment]
fixed
